export const ErrorCodes = {
  // Common / System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Authentication & Session
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',

  // Multi-Tenancy & Branches
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_EXPIRED: 'TENANT_EXPIRED',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  BRANCH_ACCESS_DENIED: 'BRANCH_ACCESS_DENIED',
  MODULE_NOT_ENABLED: 'MODULE_NOT_ENABLED',

  // RBAC
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SYSTEM_ROLE_PROTECTED: 'SYSTEM_ROLE_PROTECTED',

  // Products & Inventory
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
  PRODUCT_BARCODE_EXISTS: 'PRODUCT_BARCODE_EXISTS',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  NEGATIVE_STOCK_NOT_ALLOWED: 'NEGATIVE_STOCK_NOT_ALLOWED',

  // Devices & IMEI
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  IMEI_ALREADY_EXISTS: 'IMEI_ALREADY_EXISTS',
  DEVICE_ALREADY_SOLD: 'DEVICE_ALREADY_SOLD',
  DEVICE_NOT_IN_STOCK: 'DEVICE_NOT_IN_STOCK',

  // Grocery & Batches
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',
  BATCH_EXPIRED: 'BATCH_EXPIRED',
  BATCH_INSUFFICIENT_QTY: 'BATCH_INSUFFICIENT_QTY',

  // Library
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  BOOK_COPY_NOT_AVAILABLE: 'BOOK_COPY_NOT_AVAILABLE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_MAX_BOOKS_REACHED: 'MEMBER_MAX_BOOKS_REACHED',

  // Sales & POS
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_ALREADY_VOIDED: 'SALE_ALREADY_VOIDED',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
  REFUND_AMOUNT_EXCEEDED: 'REFUND_AMOUNT_EXCEEDED',
  DISCOUNT_LIMIT_EXCEEDED: 'DISCOUNT_LIMIT_EXCEEDED',
  PRICE_OVERRIDE_UNAUTHORIZED: 'PRICE_OVERRIDE_UNAUTHORIZED',

  // Purchasing & Suppliers
  PURCHASE_NOT_FOUND: 'PURCHASE_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  // Accounting & Daily Closing
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNTING_ENTRY_INVALID: 'ACCOUNTING_ENTRY_INVALID',
  ACCOUNTING_ENTRY_UNBALANCED: 'ACCOUNTING_ENTRY_UNBALANCED',
  DAY_ALREADY_CLOSED: 'DAY_ALREADY_CLOSED',
  DAY_NOT_CLOSED: 'DAY_NOT_CLOSED',
  TRANSACTION_LOCKED_DAY_CLOSED: 'TRANSACTION_LOCKED_DAY_CLOSED',

  // Repairs & Trade-In
  REPAIR_NOT_FOUND: 'REPAIR_NOT_FOUND',
  REPAIR_ALREADY_DELIVERED: 'REPAIR_ALREADY_DELIVERED',
  TRADEIN_NOT_FOUND: 'TRADEIN_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
